// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt-BR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	login: {
		formHeader: {
			/**
			 * L​o​g​i​n
			 */
			title: string
			subtitle: {
				/**
				 * N​o​t​ ​y​e​t​ ​a​ ​p​s​y​c​h​o​l​o​g​i​s​t​?
				 */
				text: string
				link: {
					/**
					 * S​i​g​n​ ​U​p
					 */
					text: string
				}
			}
		}
	}
	signUp: {
		formHeader: {
			/**
			 * S​i​g​n​ ​U​p
			 */
			title: string
			subtitle: {
				/**
				 * A​l​r​e​a​d​y​ ​a​ ​p​s​y​c​h​o​l​o​g​i​s​t​?
				 */
				text: string
				link: {
					/**
					 * L​o​g​i​n
					 */
					text: string
				}
			}
		}
	}
}

export type TranslationFunctions = {
	login: {
		formHeader: {
			/**
			 * Login
			 */
			title: () => LocalizedString
			subtitle: {
				/**
				 * Not yet a psychologist?
				 */
				text: () => LocalizedString
				link: {
					/**
					 * Sign Up
					 */
					text: () => LocalizedString
				}
			}
		}
	}
	signUp: {
		formHeader: {
			/**
			 * Sign Up
			 */
			title: () => LocalizedString
			subtitle: {
				/**
				 * Already a psychologist?
				 */
				text: () => LocalizedString
				link: {
					/**
					 * Login
					 */
					text: () => LocalizedString
				}
			}
		}
	}
}

export type Formatters = {}
